"""Initial migration with all tables

Revision ID: e5254db7f649
Revises: 
Create Date: 2025-09-17 11:20:09.169721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5254db7f649'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum type if it doesn't exist
    itempriority = sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='itempriority')
    itempriority.create(op.get_bind(), checkfirst=True)
    
    op.add_column('work_items', sa.Column('priority', itempriority, nullable=False, server_default='MEDIUM'))
    op.add_column('work_items', sa.Column('acceptance_criteria', sa.Text(), nullable=True))
    op.add_column('work_items', sa.Column('estimated_hours', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_items', 'estimated_hours')
    op.drop_column('work_items', 'acceptance_criteria')
    op.drop_column('work_items', 'priority')
    
    # Drop enum type
    sa.Enum(name='itempriority').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###